### ISSUE TITLE
Horizontal max height for comic on home

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/canvas#16]
need option for this css

```css
.home .main-content{
	max-height: 750px;
    max-height: 7.5rem;
}
```
